name: Weekly AI News Digest

on:
  workdlow_dispatch: {}
  push: {}
  schedule:
    - cron: '0 9 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
      uses: actions/checkout@v4

      - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser arxiv jinja2

      - name: Run script
        run: python ai_news_digest.py

      - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ai_news_digest
        path: ai_news_digest.html
